# Generated by Django 4.2.7 on 2023-11-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Верхній одяг', 'Верхній одяг'), ('Взуття', 'Взуття'), ('Штани', 'Штани'), ('Категорія', 'Категорія')], max_length=50, null=True)),
                ('quanity', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
