# Generated by Django 4.2.7 on 2023-11-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_address_profile_image_profile_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Профіль'},
        ),
    ]
